### PR TITLE
[Issue #20] Navigating to the page and the page does not start from top

### PR DESCRIPTION
**Pull request by valasubramanian-tw**
Fixed issue:

3. Look into it when clicking on any footer link and navigating to the page the page does not start from the top.

Issue link: https://github.com/koders-in/Website/issues/20

Added PageContainer component as Root component to every page, that will start the page from top.

### CODE REVIEW

**Comment by valasubramanian-tw** [comment]
@1stdevfriend Can you review this PR and merge the changes if okay for you?

**Comment by 1stdevfriend** [comment]
Hi @valasubramanian-tw. 
This PR is having conflicts with the latest commit. Can you please take a pull and push again?

**Comment by valasubramanian-tw** [comment]
> 

Done. Can you merge the PR now?

**Comment by 1stdevfriend** [comment]
Done!
Feel free to contribute in https://github.com/koders-in/website-insider or apply at koders via mailing at info@koders.in:)

**Pull request merged**
