### PR TITLE
[SEO] Labels and image descriptions

### PR DESCRIPTION
**Pull request by keerthanak-tw**
PR for the second task in #16 

This PR includes
- Image descriptions for the images used in the entire application
- Labels to link component that could be identified by screen reader

Please add the [chrome screen reader extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) and navigate through the application to see the impact 😃

### CODE REVIEW

**Comment by 1stdevfriend** [comment]
Looks good to me! 
Please go to the issue and tick on what's been done @keerthanak-tw

**Comment by keerthanak-tw** [comment]
> Looks good to me! Please go to the issue and tick on what's been done @keerthanak-tw

I tried but I think only the author can mark it to as done. I could add a separate comment and keep track of the tasks done.
Thanks @1stdevfriend for the quick review

**Comment by 1stdevfriend** [comment]
> > Looks good to me! Please go to the issue and tick on what's been done @keerthanak-tw
> 
> I tried but I think only the author can mark it to as done. I could add a separate comment and keep track of the tasks done. Thanks @1stdevfriend for the quick review

I believe that should do :)

**Comment by 1stdevfriend** [comment]
Hi @keerthanak-tw 
There are few conflicts here and there. Do take the latest pull and push again on the same pull

**Comment by keerthanak-tw** [comment]
Hello.. Done ✌️

**Comment by 1stdevfriend** [comment]
Merged :)

**Pull request merged**
