### PR TITLE
Update node version in Github actions

### PR DESCRIPTION
**Pull request by sudhinm**
#46 Updated the node version for docker/login-action, docker/setup-buildx-action, docker/build-push-action

### CODE REVIEW

**Comment by keerthanak-tw** [comment]
LGTM 👍

**Comment by 1stdevfriend** [comment]
Very small but major change haha. Let me merge that pretty quick. 

Also, feel free to pick issues from insider website.
Link - https://github.com/koders-in/Website-Insider

**Comment by 1stdevfriend** [comment]
Unforturnately, I've to revert it cause the build action is failing at v3. 

screenshot_20221027_142242

**Comment by keerthanak-tw** [comment]
Ah.. I guess i missed this!
It was v2 and not v3.. Really sorry about it

**Pull request merged**
